name: build

on: push
jobs:
  my-job:
    runs-on: actuated
    steps:
      - name: Show uptime
        run: uptime
      - name: List CPUs
        run: lscpu
      - name: Show RAM
        run: free -h
      - name: Show disk
        run: df -h /
      - name: Show kernel
        run: uname -a
      - name: Check K3s
        run: |
          curl -sLS "https://github.com/k3s-io/k3s/releases/download/v1.23.4%2Bk3s1/k3s-arm64" -o k3s
          chmod +x ./k3s
          CONFIG=/lib/modules/5.10.77/.config ./k3s check-config || :
      - name: Install k3s
        run: |
          arkade get k3sup
          $HOME/.arkade/bin/k3sup install --local
      - name: Wait until CoreDNS is ready
        run: |
          sudo -E /usr/local/bin/k3s kubectl rollout status deploy/coredns -n kube-system --timeout=300s
      - name: Get k3s nodes
        run: | 
          sudo -E /usr/local/bin/k3s kubectl get nodes -o wide
      - name: Get pods
        run: | 
          sudo -E /usr/local/bin/k3s kubectl get pods -A -o wide
      - name: debug
        run: sleep 120

