name: build

on: push
jobs:
  my-job:
    runs-on: self-hosted
    steps:
      - name: Get remote nodeinfo
        run: curl -sLS https://faasd.exit.o6s.io/function/nodeinfo
      - name: Check K3s
        run: |
          curl -sLS "https://github.com/k3s-io/k3s/releases/download/v1.23.4%2Bk3s1/k3s-arm64" -o k3s
          chmod +x ./k3s
          CONFIG=/lib/modules/5.10.77/.config ./k3s check-config check-config || :
      - name: debug
        run: sleep 240
